import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "@/component/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />  
        {children}
      </body>
    </html>
  );
}
